// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculator.Data.Contexts;

#nullable disable

namespace TaxCalculator.Data.Migrations
{
    [DbContext(typeof(TaxCalculatorContext))]
    partial class TaxCalculatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxCalculator.Data.Models.TaxCalculatorHistory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AnnualTaxPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal>("GrossAnnualSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GrossMonthlySalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MonthlyTaxPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NetAnnualSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NetMonthlySalary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("TaxHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
